/**
 * Generate facilitator guide PDF for retrospective
 * Adapted from teammomentum design (orange theme, premium layout)
 */

import { jsPDF } from 'jspdf'
import type { RetroPlan, ActivitySelection } from '@/lib/retro/activity-selector'
import type { Pattern } from '@/lib/retro/patterns'

export interface PDFTemplate {
  problem: string
  description: string
  totalDuration: number
  activities: Array<{
    name: string
    phase: string
    duration: number
    description: string
    instructions: string
    materials?: string[]
    facilitatorTips?: string[]
    difficulty?: string
  }>
  tips?: string[]
}

const PHASE_NAMES: Record<string, { en: string; fr: string }> = {
  'Set the stage': { en: 'Set the Stage', fr: 'Créer le Contexte' },
  'Gather data': { en: 'Gather Data', fr: 'Collecter les Données' },
  'Generate insights': { en: 'Generate Insights', fr: 'Générer des Insights' },
  'Decide what to do': { en: 'Decide What to Do', fr: 'Décider Quoi Faire' },
  'Close the retro': { en: 'Close the Retro', fr: 'Clore la Rétro' }
}

/** Pattern minimal pour le PDF (name, description) */
type PatternForPDF = Pick<Pattern, 'name' | 'nameFr' | 'description' | 'descriptionFr'>

/**
 * Build PDF template from RetroPlan + pattern (for questionnaire mode)
 */
export function buildRetroPDFTemplate(
  retroPlan: RetroPlan,
  primaryPattern: PatternForPDF | null,
  lang: 'en' | 'fr'
): PDFTemplate {
  const problem = primaryPattern
    ? (lang === 'fr' ? primaryPattern.nameFr : primaryPattern.name)
    : (lang === 'fr' ? 'Rétrospective Aléatoire' : 'Random Retrospective')

  const description = primaryPattern
    ? (lang === 'fr' ? primaryPattern.descriptionFr : primaryPattern.description)
    : (lang === 'fr'
        ? 'Rétrospective générée pour explorer différents aspects de la collaboration.'
        : 'Retrospective generated to explore different aspects of collaboration.')

  const activities = retroPlan.activities.map((sel: ActivitySelection) => {
    const phaseName = PHASE_NAMES[sel.phase] || { en: sel.phase, fr: sel.phase }
    const phase = lang === 'fr' ? phaseName.fr : phaseName.en
    const name = lang === 'fr' ? sel.activity.nameFr : sel.activity.name
    const desc = lang === 'fr' ? sel.activity.summaryFr : sel.activity.summary
    const instructions = lang === 'fr' ? sel.activity.descriptionFr : sel.activity.description

    return {
      name,
      phase,
      duration: sel.allocatedTime,
      description: desc,
      instructions,
      materials: [],
      facilitatorTips: [],
      difficulty: lang === 'fr' ? 'Moyen' : 'Medium'
    }
  })

  return {
    problem,
    description,
    totalDuration: retroPlan.totalTime,
    activities,
    tips: []
  }
}

/**
 * Generate PDF document from template
 */
function generateRetroPDFDoc(
  template: PDFTemplate,
  lang: 'en' | 'fr',
  teamSize: number | string | null
): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  })

  const t = {
    fr: {
      title: 'Guide Facilitateur',
      subtitle: 'Rétrospective Personnalisée',
      problem: 'Problème identifié',
      duration: 'Durée totale',
      activities: 'Activités',
      activity: 'Activité',
      phase: 'Phase',
      instructions: 'Instructions détaillées',
      materials: 'Matériel nécessaire',
      tips: 'Conseils facilitateur',
      generalTips: 'Conseils généraux',
      difficulty: 'Difficulté',
      time: 'Durée',
      footer: 'Généré par AIgile - aigile.fr/retro',
      page: 'Page',
      generated: 'Généré le',
      teamSize: 'Équipe'
    },
    en: {
      title: 'Facilitator Guide',
      subtitle: 'Personalized Retrospective',
      problem: 'Identified problem',
      duration: 'Total duration',
      activities: 'Activities',
      activity: 'Activity',
      phase: 'Phase',
      instructions: 'Detailed instructions',
      materials: 'Materials needed',
      tips: 'Facilitator tips',
      generalTips: 'General tips',
      difficulty: 'Difficulty',
      time: 'Duration',
      footer: 'Generated by AIgile - aigile.fr/retro',
      page: 'Page',
      generated: 'Generated on',
      teamSize: 'Team'
    }
  }

  const content = t[lang]
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let y = margin

  const colors = {
    orange: [249, 115, 22] as [number, number, number],
    darkGray: [30, 30, 30] as [number, number, number],
    lightGray: [100, 100, 100] as [number, number, number],
    blue: [59, 130, 246] as [number, number, number],
    green: [34, 197, 94] as [number, number, number]
  }

  const getPageCount = () => (doc as { internal: { getNumberOfPages?: () => number; pages?: unknown[] } }).internal.getNumberOfPages?.() ?? (doc as { internal: { pages: unknown[] } }).internal.pages?.length ?? 1
  const addFooter = (pageNum?: number) => {
    const p = pageNum ?? getPageCount()
    const footerY = pageHeight - 10
    
    doc.setFontSize(7)
    doc.setTextColor(...colors.lightGray)
    
    const now = new Date()
    const dateStr = now.toLocaleDateString(lang === 'fr' ? 'fr-FR' : 'en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })
    const timeStr = now.toLocaleTimeString(lang === 'fr' ? 'fr-FR' : 'en-US', {
      hour: '2-digit',
      minute: '2-digit'
    })
    
    let footerText = `${content.generated} ${dateStr} ${lang === 'fr' ? 'à' : 'at'} ${timeStr}`
    if (teamSize != null) {
      footerText += ` • ${content.teamSize}: ${teamSize}`
    }
    
    doc.text(footerText, pageWidth / 2, footerY - 6, { align: 'center' })
    doc.text(
      `${content.footer} • ${content.page} ${p}`,
      pageWidth / 2,
      footerY,
      { align: 'center' }
    )
  }

  const checkNewPage = (requiredHeight: number) => {
    if (y + requiredHeight > pageHeight - margin) {
      addFooter()
      doc.addPage()
      y = margin
      return true
    }
    return false
  }

  // Cover page
  doc.setFillColor(...colors.orange)
  doc.rect(0, 0, pageWidth, 60, 'F')

  y = 35
  doc.setFontSize(28)
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.text(content.title, pageWidth / 2, y, { align: 'center' })

  y += 10
  doc.setFontSize(16)
  doc.setFont('helvetica', 'normal')
  doc.text(content.subtitle, pageWidth / 2, y, { align: 'center' })

  y = 80

  // Main info
  doc.setFontSize(14)
  doc.setTextColor(...colors.darkGray)
  doc.setFont('helvetica', 'bold')
  doc.text(`${content.problem}:`, margin, y)

  y += 8
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...colors.orange)
  const problemLines = doc.splitTextToSize(template.problem, contentWidth)
  doc.text(problemLines, margin, y)
  y += problemLines.length * 6 + 5

  doc.setFontSize(10)
  doc.setTextColor(...colors.darkGray)
  const descLines = doc.splitTextToSize(template.description, contentWidth)
  doc.text(descLines, margin, y)
  y += descLines.length * 5 + 10

  doc.setFontSize(10)
  doc.setTextColor(...colors.lightGray)
  doc.text(
    `${content.duration}: ${template.totalDuration} ${lang === 'fr' ? 'minutes' : 'minutes'}`,
    margin,
    y
  )
  y += 6
  doc.text(`${content.activities}: ${template.activities.length}`, margin, y)
  y += 15

  doc.setDrawColor(...colors.orange)
  doc.setLineWidth(0.5)
  doc.line(margin, y, pageWidth - margin, y)
  y += 10

  // Activities
  template.activities.forEach((activity, index) => {
    checkNewPage(80)

    doc.setFillColor(...colors.orange)
    doc.circle(margin + 5, y, 8, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(String(index + 1), margin + 5, y + 2, { align: 'center' })

    doc.setTextColor(...colors.darkGray)
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    const titleLines = doc.splitTextToSize(activity.name, contentWidth - 20)
    doc.text(titleLines, margin + 15, y)
    y += titleLines.length * 7 + 3

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...colors.orange)
    doc.text(activity.phase, margin + 15, y)

    const metaX = margin + 15 + doc.getTextWidth(activity.phase) + 10
    doc.setTextColor(...colors.lightGray)
    doc.text(
      `• ${activity.duration} ${lang === 'fr' ? 'min' : 'min'}`,
      metaX,
      y
    )

    if (activity.difficulty) {
      const difficultyX = metaX + doc.getTextWidth(`• ${activity.duration} min `) + 5
      doc.text(`• ${activity.difficulty}`, difficultyX, y)
    }

    y += 8

    doc.setFontSize(10)
    doc.setTextColor(...colors.darkGray)
    const activityDescLines = doc.splitTextToSize(activity.description, contentWidth - 20)
    doc.text(activityDescLines, margin + 15, y)
    y += activityDescLines.length * 5 + 8

    if (activity.materials && activity.materials.length > 0) {
      checkNewPage(30)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...colors.blue)
      doc.text(`${content.materials}:`, margin + 15, y)
      y += 6

      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...colors.darkGray)
      activity.materials.forEach((material) => {
        doc.text(`• ${material}`, margin + 20, y)
        y += 5
      })
      y += 3
    }

    checkNewPage(50)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...colors.orange)
    doc.text(`${content.instructions}:`, margin + 15, y)
    y += 7

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...colors.darkGray)

    const instructions = activity.instructions || ''
    const lines = instructions.split('\n').filter((line) => line.trim())

    lines.forEach((line) => {
      const trimmed = line.trim()
      const stepMatch = trimmed.match(/^(\d+)\.\s*(.+)/)
      if (stepMatch) {
        checkNewPage(15)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...colors.orange)
        doc.text(`${stepMatch[1]}. ${stepMatch[2]}`, margin + 20, y)
        y += 6
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...colors.darkGray)
      } else if (trimmed.startsWith('-') || trimmed.startsWith('•')) {
        checkNewPage(8)
        doc.text(`  ${trimmed.substring(1).trim()}`, margin + 25, y)
        y += 5
      } else if (trimmed) {
        checkNewPage(8)
        const wrappedLines = doc.splitTextToSize(trimmed, contentWidth - 30)
        doc.text(wrappedLines, margin + 20, y)
        y += wrappedLines.length * 5
      }
    })

    if (activity.facilitatorTips && activity.facilitatorTips.length > 0) {
      checkNewPage(30)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...colors.green)
      doc.text(`${content.tips}:`, margin + 15, y)
      y += 6

      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...colors.darkGray)
      activity.facilitatorTips.forEach((tip) => {
        checkNewPage(8)
        const tipLines = doc.splitTextToSize(`• ${tip}`, contentWidth - 30)
        doc.text(tipLines, margin + 20, y)
        y += tipLines.length * 5
      })
      y += 5
    }

    y += 10

    if (index < template.activities.length - 1) {
      checkNewPage(5)
      doc.setDrawColor(200, 200, 200)
      doc.setLineWidth(0.2)
      doc.line(margin, y, pageWidth - margin, y)
      y += 8
    }
  })

  if (template.tips && template.tips.length > 0) {
    checkNewPage(50)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...colors.orange)
    doc.text(content.generalTips, margin, y)
    y += 10

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...colors.darkGray)
    template.tips.forEach((tip) => {
      checkNewPage(10)
      const tipLines = doc.splitTextToSize(`• ${tip}`, contentWidth)
      doc.text(tipLines, margin + 5, y)
      y += tipLines.length * 5 + 3
    })
  }

  const pageCount = getPageCount()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    addFooter(i)
  }

  return doc
}

/**
 * Download retro PDF as file
 */
export async function downloadRetroPDF(
  retroPlan: RetroPlan,
  primaryPattern: PatternForPDF | null,
  lang: 'en' | 'fr',
  teamSize: number
): Promise<void> {
  const template = buildRetroPDFTemplate(retroPlan, primaryPattern, lang)
  const pdf = generateRetroPDFDoc(template, lang, teamSize)

  const problemSlug = template.problem
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  const filename = `retro-${problemSlug}-${Date.now()}.pdf`
  pdf.save(filename)
}
